version: '2'
networks:
  default:
    driver: bridge
services:
  nextcloud:
    image: wonderfall/nextcloud
    container_name: nextcloud
    depends_on:
      - nextcloud-db           # If using MySQL
    ports:
      - "33388:8888"
    environment:
      - UID=1000
      - GID=1000
      - UPLOAD_MAX_SIZE=10G
      - APC_SHM_SIZE=128M
      - OPCACHE_MEM_SIZE=128
      - CRON_PERIOD=15m
      - TZ=Europe/Berlin
      - ADMIN_USER=admin            # Don't set to configure through browser
      - ADMIN_PASSWORD=123456        # Don't set to configure through browser
      - DOMAIN=localhost
      - DB_TYPE=mysql
      - DB_NAME=nextcloud
      - DB_USER=nextcloud
      - DB_PASSWORD=123456
      - DB_HOST=nextcloud-db
    volumes:
      - ./nextcloud/data:/data
      - ./nextcloud/config:/config
      - ./nextcloud/apps:/apps2
      - ./nextcloud/themes:/nextcloud/themes

  nextcloud-db:
    image: mariadb:10
    container_name: mariadb
    volumes:
      - ./nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=123456
