version: '2'
services:
  nginx:
    image: nginx:1.12.2
    container_name: nginx
    depends_on:
      - php
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx:/etc/nginx/conf.d/
      - ./html/var/www/html
    restart: always
    hostname: nginx.docker

  php:
    image: byeyouth/php:7.2
    #image: php:7.2.0-fpm
    container_name: php
    volumes:
      - ./html:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/zz.conf:/usr/local/etc/php-fpm.d/zz.conf
    restart: always
    hostname: php.docker
